apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgproxy
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: 5m
        sidecar.istio.io/proxyCPULimit: 500m
      labels:
        version: 5c844dd
    spec:
      serviceAccountName: imgproxy

      containers:
      - name: imgproxy
        image: darthsim/imgproxy:latest@sha256:5c844ddaf98ca33bf70072a0b66f94cf14bb2c68787adbfa73e076d69d9d1a89
        env:
        - name: IMGPROXY_USE_GCS
          value: "true"
        - name: IMGPROXY_PROMETHEUS_BIND
          value: "0.0.0.0:9000"
        ports:
        - name: http
          containerPort: 8080
        - name: http-prometheus
          containerPort: 9000

        resources:
          requests:
            cpu: 5m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 200Mi
