apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgproxy
spec:
  template:
    metadata:
      annotations:
        sidecar.istio.io/proxyCPU: 5m
        sidecar.istio.io/proxyCPULimit: 500m
      labels:
        version: 5c844dd
    spec:
      serviceAccountName: imgproxy

      containers:
      - name: imgproxy
        image: darthsim/imgproxy:v2.16.4@sha256:160db382092e9d00d84337d4569e09031138d2cadc62b8571d0714d36211ec1a
        env:
        - name: IMGPROXY_USE_GCS
          value: "true"
        - name: IMGPROXY_PROMETHEUS_BIND
          value: "0.0.0.0:9000"
        - name: IMGPROXY_TTL
          value: "31536000"
        ports:
        - name: http
          containerPort: 8080
        - name: http-prometheus
          containerPort: 9000

        resources:
          requests:
            cpu: 5m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 200Mi
