---
jobs:

- name: backup-postgres-databases
  plan:
  - get: repo
  - task: backup
    file: repo/ci/tasks/backup-postgres.yaml
    params:
      PGDATABASE: affable
      PGHOST: unhinged
      PGUSER: affable
  - put: code-supply-backups
    params:
      file: backups/*.tar.bz2

resources:

- name: repo
  type: git
  source:
    uri: https://github.com/code-supply/code-supply
    branch: main

- name: code-supply-backups
  type: gcs
  source:
    bucket: code-supply-backups
    json_key: ((google-key))
    versioned_file: postgres/backup.tar.bz2

resource_types:

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource
    tag: v0.6.0
