---
jobs:

- name: backup-hosting
  plan:
  - get: daily
    trigger: true
  - get: repo
  - task: backup
    file: repo/ci/tasks/postgres-backup.yaml
    params:
      PGDATABASE: hosting
      PGHOST: unhinged
      PGUSER: hosting
  - put: backup-hosting
    params:
      file: backups/*.tar.bz2

- name: test-restore-hosting
  plan:
  - get: repo
  - get: backups
    resource: backup-hosting
    trigger: true
    passed: [backup-hosting]
  - task: prepare
    file: repo/ci/tasks/postgres-prepare-restore.yaml
    vars:
      database: hosting
      user: hosting
      test-query: select * from users where email = 'me@andrewbruce.net'
  - task: restore-test
    file: repo/ci/tasks/postgres-restore.yaml
    vars:
      database: hosting

- name: backup-atc
  plan:
  - get: daily
    trigger: true
  - get: repo
  - task: backup
    file: repo/ci/tasks/postgres-backup.yaml
    params:
      PGDATABASE: atc
      PGHOST: unhinged
      PGUSER: concourse
  - put: backup-atc
    params:
      file: backups/*.tar.bz2

- name: test-restore-atc
  plan:
  - get: repo
  - get: backups
    resource: backup-atc
    trigger: true
    passed: [backup-atc]
  - task: prepare
    file: repo/ci/tasks/postgres-prepare-restore.yaml
    vars:
      database: atc
      user: concourse
      test-query: select * from users where username = 'camelpunch'
  - task: restore-test
    file: repo/ci/tasks/postgres-restore.yaml
    vars:
      database: atc

resources:

- name: repo
  type: git
  source:
    uri: https://github.com/code-supply/code-supply
    branch: main

- name: backup-hosting
  type: gcs
  source:
    bucket: code-supply-backups
    json_key: ((google-key))
    versioned_file: postgres/hosting.tar.bz2

- name: backup-atc
  type: gcs
  source:
    bucket: code-supply-backups
    json_key: ((google-key))
    versioned_file: postgres/atc.tar.bz2

- name: daily
  type: time

resource_types:

- name: gcs
  type: registry-image
  source:
    repository: frodenas/gcs-resource
    tag: v0.6.0
