#!/usr/bin/env bash

while inotifywait -qq -e attrib src/*
do
  cp src/*.html dev-dist/
  echo "Copied stuff to dev-dist"
done &

tailwindcss -i src/input.css -o dev-dist/app.css --watch --content src/index.html

wait
