#!/usr/bin/env bash

tailwind-linux-x64 -i src/input.css -o dist/output.css --watch --content src/index.html &

while inotifywait -qq -e attrib src/*
do
  cp src/*.html dist/
  active_window_id="$(xdotool getwindowfocus)"
  target_window_id="$(xdotool search --name index.html)"

  xdotool windowactivate "$target_window_id"
  xdotool key F5
  xdotool windowactivate "$active_window_id"
done

wait
