kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: affable-www
spec:
  secretName: affable-www
  issuerRef:
    name: letsencrypt-production-dns
    kind: ClusterIssuer
  commonName: "*.affable.app"
  dnsNames:
  - "*.affable.app"
  - affable.app
