apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-control-plane
spec:
  profile: default
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
    accessLogEncoding: JSON
  components:
    pilot:
      k8s:
        resources:
          requests:
            memory: 49Mi
            cpu: 5m
          limits:
            memory: 500Mi
            cpu: 500m
    egressGateways:
    - name: istio-egressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 3m
            memory: 43Mi
          limits:
            memory: 100Mi
    ingressGateways:
    - name: istio-ingressgateway-nodeport
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 5m
            memory: 43Mi
          limits:
            memory: 100Mi
        service:
          type: NodePort
        serviceAnnotations:
          cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
    - name: istio-ingressgateway
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 5m
            memory: 43Mi
          limits:
            memory: 100Mi
