apiVersion: v1
kind: Service
metadata:
  name: hosting-headless
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 5555
    name: tcp-erlang
    targetPort: tcp-erlang
  - port: 4369
    name: tcp-epmd
    targetPort: tcp-epmd
