apiVersion: v1
kind: Service
metadata:
  name: hosting
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: http
  ipFamilies:
  - IPv4
  - IPv6
  ipFamilyPolicy: PreferDualStack
