apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affable
resources:
- namespace.yaml
- service-account.yaml
- service.yaml
- deployment.yaml
- headless-service.yaml
- rbac.yaml
- certificate.yaml
replicas:
- count: 3
  name: affable
commonLabels:
  app: affable
images:
- name: affable
  newName: eu.gcr.io/code-supply/affable
  newTag: 9c12350
patchesStrategicMerge:
- version.yaml
