apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: affable
resources:
- namespace.yaml
- service-account.yaml
- service.yaml
- deployment.yaml
- headless-service.yaml
- gateway.yaml
- virtual-service.yaml
- cloud-sql-egress.yaml
- googleapis-egress.yaml
- google-metadata-egress.yaml
- google-oauth2-api-egress.yaml
- google-sql-api-egress.yaml
- sendgrid-api-egress.yaml
- rbac.yaml
replicas:
- count: 2
  name: affable
commonLabels:
  app: affable
images:
- name: affable
  newName: eu.gcr.io/code-supply/affable
  newTag: d9419bc
patchesStrategicMerge:
- version.yaml
- istio-proxy-resources.yaml
