---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: affable
rules:
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - endpoints
  verbs:
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: affable-can-manage-sites
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: affable
subjects:
- kind: ServiceAccount
  name: affable
