#!/usr/bin/env bash

set -eu

cwd="$(dirname "$0")"

"$cwd/sd-build"

umount "/run/media/$USER/"* || true

unzstd \
  < sdcard-result/sd-image/nixos-image-sd-card-*aarch64-linux.img.zst \
  | pv \
  > /dev/mmcblk0
