# The URL the site will be built for
base_url = "https://www.andrewbruce.net"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "lightspeed"

title = "Andrew Bruce"
description = "A software person"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
zola = ""
maintained_with_love = false

[[extra.footer_links]]
name = "Email"
url = "mailto:me@andrewbruce.net"

[[extra.footer_links]]
name = "GitHub"
url = "https://github.com/camelpunch"

[[extra.footer_links]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/fartypants"
