#!/usr/bin/env bash

pids=""
for n in {1..5}
do
    MIX_TEST_PARTITION=$n mix test --partitions 5 &
    pids+=" $!"
done

for p in $pids
do
    if ! wait $p
    then
        echo "Some tests failed"
        exit 1
    fi
done
