---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: watch-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tls-lb-operator-can-watch-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: watch-secrets
subjects:
- kind: ServiceAccount
  name: tls-lb-operator
