kind: ClusterIssuer
apiVersion: cert-manager.io/v1
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tech@code.supply
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          name: load-balancer-affable
    - dns01:
        cloudDNS:
          project: code-supply
          serviceAccountSecretRef:
            name: clouddns
            key: code-supply-cc2de6fd7943.json
