#!/usr/bin/env bash

if [ "$1" = "--config" ]
then
  cat <<EOF
configVersion: v1
kubernetes:
- apiVersion: v1
  kind: Secret
  executeHookOnEvent: [Added, Deleted]
  namespace:
    nameSelector:
      matchNames: [affable]
EOF
else
  jq --raw-output < "$BINDING_CONTEXT_PATH"
fi
