#!/usr/bin/env bash

if [ "$1" = "--config" ]
then
  cat <<EOF
configVersion: v1
kubernetes:
- apiVersion: v1
  kind: Secret
  executeHookOnEvent: [Added, Deleted]
  namespace:
    nameSelector:
      matchNames: [affable]
EOF
else
  secret_name="$(jq --raw-output .[0].object.metadata.name "$BINDING_CONTEXT_PATH")"
  echo "Secret $secret_name added"
fi
